spring:
  main.banner-mode: "off"
  h2.console.enabled: true
  jpa:
    # Disabled since a filter is declared programmatically
    open-in-view: false
    show-sql: true

logging.level:
  ROOT: INFO
#  org.springframework: DEBUG
#  org.hibernate: DEBUG
