spring:
  # Uncomment to use a file based DB instead of the default "jdbc:h2:mem:testdb" in-memory DB
#  datasource.url: jdbc:h2:file:~/data/h2/spring-graphql-sample
  # Uncomment to add logging
#  datasource.url: jdbc:h2:mem:testdb;TRACE_LEVEL_FILE=4
  h2.console.enabled: true
  jpa:
    open-in-view: true
    show-sql: true

logging.level:
  ROOT: INFO
#  org.springframework: DEBUG
#  org.hibernate: DEBUG
#  graphql: DEBUG
